server:
  port: 8092

spring:
  application:
    name: HOTEL-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/hotel-service?createDatabaseIfNotExist=true
    username: root
    password: Root@1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

okta:
  oauth2:
    issuer: https://dev-54450627.okta.com/oauth2/default
    audience: api://default