server:
  port: 8091

spring:
  application:
    name: USER-SERVICE
#  profiles:
#    active: dev

  datasource:
    url: jdbc:mysql://localhost:3306/user-service?createDatabaseIfNotExist=true
    username: root
    password: Root@1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  ## This config fetch from Config Server git repo
  config:
    import: configserver:http://localhost:8085

## This config fetch from Config Server git repo
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/

