server:
  port: 8091

spring:
  application:
    name: USER-SERVICE
#  profiles:
#    active: dev

  datasource:
    url: jdbc:mysql://localhost:3306/user-service?createDatabaseIfNotExist=true
    username: root
    password: Root@1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

## OAuth2 Client Configuration which can call other API
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: https://dev-54450627.okta.com/oauth2/default
      client:
        registration:
          my-internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope:
              - internal
            client-id: 0oadl86cqp9DdWqHc5d7
            client-secret: cKCTXo1swtnSthAoRmUXZ_UEuaU6Zq8V1XN0TfupwP-9c8AQdulk-53Qo5w88C50
        provider:
          okta:
            issuer-uri: https://dev-54450627.okta.com/oauth2/default

  ## This config fetch from Config Server git repo
  config:
    import: configserver:http://localhost:8085

## This config fetch from Config Server git repo
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/

## Actuators config
management:
  health:
    circuit-breakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

## Resilience4J circuit breaker config
resilience4j:
  circuit-breaker:
    instances:
      ratingHotelBreaker:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state:
          seconds: 5
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED

  retry:
    instances:
      ratingHotelService:
        max-attempts: 3
        wait-duration:
          seconds: 3

  rate-limiter:
    instances:
      userRateLimiter:
        limit-refresh-period:
          seconds: 4
        limit-for-period: 2
        timeout-duration:
          seconds: 2

okta:
  oauth2:
    issuer: https://dev-54450627.okta.com/oauth2/default
    audience: api://default
